fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
  symlinks:
    "mailhog": "#{source_dir}"
